[env:esp32-s3-wroom-1-n16r8]
platform = espressif32@6.11.0
board = esp32-s3-devkitc-1
framework = arduino, espidf

extra_scripts =
    pre:scripts/get_software_version.py
    post:scripts/ota_packager.py
    scripts/pio_extra_commands.py

build_unflags =
    -std=gnu++11

build_flags =
    -include src/undef_ip.h
    -UIPADDR_NONE
    -UINADDR_NONE
    -DCONFIG_ESP32_JTAG_ENABLE=0
    -Wno-deprecated-declarations
    -DOPENWEATHER_API_KEY=\"3f2ef88da8403bdccc2816676dfe3ef1\"
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_VARIANT=\"esp32s3\"
    -DBOARD_HAS_PSRAM

board_build.partitions = partitions.csv
board_build.filesystem = spiffs

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

board_build.arduino.variant = esp32s3
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

monitor_speed = 115200