[env:esp32-s3-wroom-1-n16r8]
platform = espressif32@6.11.0
board    = esp32-s3-devkitc-1 
framework = arduino

extra_scripts = 
    -pre:scripts/get_software_version.py
    -post:scripts/ota_packager.py
     scripts/pio_extra_commands.py

build_unflags = 
  -std=gnu++11

build_flags =
  -DCONFIG_USE_TRACE_FACILITY=1
  -DCONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
  -DCONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS=1
  -DCONFIG_FREERTOS_USE_IDLE_HOOK=1
  -include src/undef_ip.h
  -UIPADDR_NONE
  -UINADDR_NONE
  -DBOARD_HAS_PSRAM
  -DCONFIG_ESP32_JTAG_ENABLE=0
  -mfix-esp32-psram-cache-issue
  -Wno-deprecated-declarations
  -DOPENWEATHER_API_KEY=\"3f2ef88da8403bdccc2816676dfe3ef1\"
  -std=gnu++17

board_build.partitions              = partitions.csv
board_build.filesystem              = spiffs

board_build.flash_mode              = qio
board_upload.flash_size             = 16MB
board_upload.maximum_size           = 16777216

board_build.arduino.memory_type     = qio_opi  
board_build.psram_type              = opi      
board_build.extra_flags             = -DBOARD_HAS_PSRAM

monitor_speed                       = 115200 