[env:esp32-s3-wroom-1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = espidf

extra_scripts =
    pre:scripts/get_software_version.py
    post:scripts/ota_packager.py
    scripts/pio_extra_commands.py

build_unflags =
    -std=gnu++11

build_flags =
    -include src/undef_ip.h
    -UIPADDR_NONE
    -UINADDR_NONE
    -DCONFIG_ESP32_JTAG_ENABLE=0
    -std=gnu++17

board_build.partitions = partitions.csv
board_build.filesystem = spiffs

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

board_build.psram_type = opi

monitor_speed = 115200
